(function(){
const VER='v1.4.17';
const CHOICES=[30,60,90,120,150,180,210];
let selectedCell=null,selectedId='',timer=null,patched=false;
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const css=s=>window.CSS&&CSS.escape?CSS.escape(s):String(s).replace(/["\\]/g,'\\$&');
const cfg=()=>window.WNMU_MONTHLY_PAGE_CONFIG||{};
const storeKey=()=>cfg().storageKey||'';
const metaKey=()=>storeKey()?`${storeKey()}::manualRectMeta.v1.4.17`:'';
function read(k,fb={}){try{let r=k&&localStorage.getItem(k);return r?JSON.parse(r):fb}catch{return fb}}
function write(k,v){if(k)localStorage.setItem(k,JSON.stringify(v||{}))}
const marks=()=>read(storeKey(),{}), meta=()=>read(metaKey(),{}), choice=n=>CHOICES.reduce((b,c)=>Math.abs(c-(+n||30))<Math.abs(b-(+n||30))?c:b,CHOICES[0]);
function rectFor(id){let m=marks(), mt=meta(), e=m[id]||{}, r=e.rectNote; return r?{...r,...(mt[id]||{})}:null}
function controls(){let rt=document.querySelector('.rect-tools'); if(!rt||document.getElementById('manualRectDurationTools'))return; let p=document.createElement('div'); p.id='manualRectDurationTools'; p.className='manual-rect-duration-tools'; p.innerHTML=`<div class="manual-rect-label">Box note length</div><div class="manual-rect-duration-options">${CHOICES.map(n=>`<label class="manual-rect-pill"><input type="radio" name="manualRectDuration" value="${n}"><span>${n}</span></label>`).join('')}</div><div class="manual-rect-label">Anchor</div><div class="manual-rect-anchor-options"><label class="manual-rect-pill"><input type="radio" name="manualRectAnchor" value="left" checked><span>upper left</span></label><label class="manual-rect-pill"><input type="radio" name="manualRectAnchor" value="right"><span>upper right</span></label></div><label class="manual-rect-label" for="manualRectText">Box note text</label><textarea id="manualRectText" class="manual-rect-text" rows="3" placeholder="Type the note to draw in the box"></textarea><div class="manual-rect-help">Starts at the top corner of the program cell you right-clicked. The chosen length controls how far down the white note box draws.</div>`; rt.insertBefore(p,rt.querySelector('.rect-actions')||null); let b=document.getElementById('drawRectBtn'); if(b)b.textContent='Save box note'}
function setCtrls(id,cell){controls(); let r=id&&rectFor(id); let dur=choice(r?.durationMin || Math.max(1,+(cell?.rowSpan||1))*30), anc=r?.anchor==='right'?'right':'left'; let d=document.querySelector(`input[name="manualRectDuration"][value="${dur}"]`); if(d)d.checked=true; let a=document.querySelector(`input[name="manualRectAnchor"][value="${anc}"]`); if(a)a.checked=true; let t=document.getElementById('manualRectText'); if(t)t.value=r?.text||''; let s=document.getElementById('rectStatus'); if(s&&r)s.textContent=`Box note saved. Length: ${dur} min. Anchor: upper ${anc}.`}
function patchStorage(){if(patched)return; patched=true; let orig=Storage.prototype.setItem; Storage.prototype.setItem=function(k,v){try{if(k===storeKey()){let mt=read(metaKey(),{}), obj=JSON.parse(String(v||'{}')); Object.entries(mt).forEach(([id,x])=>{if(obj[id]?.rectNote)obj[id].rectNote={...obj[id].rectNote,...x}}); v=JSON.stringify(obj)}}catch{} let out=orig.apply(this,[k,v]); if(k===storeKey())renderSoon(); return out}}
function saveNote(){if(!selectedId||!storeKey())return; let dur=choice(document.querySelector('input[name="manualRectDuration"]:checked')?.value||30), anc=document.querySelector('input[name="manualRectAnchor"]:checked')?.value==='right'?'right':'left', text=(document.getElementById('manualRectText')?.value||'').trim(); let m=marks(), mt=meta(), e=m[selectedId]&&typeof m[selectedId]==='object'?m[selectedId]:{}; e.rectNote={x:anc==='right'?6:4,y:4,w:90,h:90,text,durationMin:dur,anchor:anc,manualDuration:true,anchorMode:anc==='right'?'upper-right':'upper-left'}; m[selectedId]=e; mt[selectedId]={durationMin:dur,anchor:anc,manualDuration:true,anchorMode:e.rectNote.anchorMode}; write(metaKey(),mt); write(storeKey(),m); setCtrls(selectedId,selectedCell); renderSoon(); let menu=document.getElementById('contextMenu'); if(menu){menu.classList.add('hidden');menu.setAttribute('aria-hidden','true')}}
function renderSoon(){clearTimeout(timer);timer=setTimeout(render,120)}
function overlay(cell,r){let wrap=cell.closest('.week-grid-wrap')||cell.closest('.screen-host')||cell.offsetParent; if(!wrap)return; let cr=cell.getBoundingClientRect(), wr=wrap.getBoundingClientRect(); if(!cr.width||!cr.height)return; let slots=Math.max(1,+(cell.rowSpan||1)), slotH=cr.height/slots, dur=choice(r.durationMin||slots*30), h=Math.max(18,slotH*Math.round(dur/30)-4), w=Math.max(40,cr.width-8), top=cr.top-wr.top+2, left=r.anchor==='right'?cr.right-wr.left-w-4:cr.left-wr.left+4; let box=document.createElement('div'); box.className='wnmu-manual-note-overlay'; box.dataset.entryId=cell.dataset.entryId||''; box.style.cssText=`left:${left}px;top:${top}px;width:${w}px;height:${h}px`; box.innerHTML=`<div class="wnmu-manual-note-text">${esc(r.text||'')}</div><div class="wnmu-manual-note-duration">${dur} min</div>`; wrap.appendChild(box)}
function render(){document.body.classList.add('wnmu-manual-note-overlay-active'); document.querySelectorAll('.wnmu-manual-note-overlay').forEach(x=>x.remove()); let m=marks(); Object.entries(m).forEach(([id,e])=>{if(!e?.rectNote)return; let r=rectFor(id); document.querySelectorAll(`.program-cell[data-entry-id="${css(id)}"]`).forEach(c=>{let b=c.getBoundingClientRect(); if(b.width&&b.height)overlay(c,r)})})}
function styles(){if(document.getElementById('manualNoteBoxDurationStyles'))return; let st=document.createElement('style'); st.id='manualNoteBoxDurationStyles'; st.textContent=`.manual-rect-duration-tools{border:1px solid rgba(255,255,255,.22);border-radius:10px;padding:10px;margin:10px 0;background:rgba(255,255,255,.06)}.manual-rect-label{font-size:12px;font-weight:800;margin:6px 0 5px}.manual-rect-duration-options,.manual-rect-anchor-options{display:flex;flex-wrap:wrap;gap:5px}.manual-rect-pill{display:inline-flex;align-items:center;gap:3px;font-size:12px;border:1px solid rgba(255,255,255,.24);border-radius:999px;padding:4px 7px;cursor:pointer}.manual-rect-pill input{margin:0}.manual-rect-text{width:100%;box-sizing:border-box;border-radius:8px;border:1px solid rgba(255,255,255,.28);padding:7px;resize:vertical;font:13px/1.3 system-ui,sans-serif;color:#111;background:#fff}.manual-rect-help{margin-top:6px;font-size:11px;opacity:.75;line-height:1.25}.week-grid-wrap{position:relative}body.wnmu-manual-note-overlay-active .program-cell>.draw-rect-note{display:none!important}.wnmu-manual-note-overlay{position:absolute;z-index:30;pointer-events:none;box-sizing:border-box;border:2px solid rgba(10,20,40,.75);background:rgba(255,255,255,.93);color:#111;border-radius:4px;box-shadow:0 2px 5px rgba(0,0,0,.18);overflow:hidden;padding:4px 5px 14px;font:12px/1.2 system-ui,sans-serif}.wnmu-manual-note-text{white-space:normal;overflow:hidden}.wnmu-manual-note-duration{position:absolute;right:4px;bottom:2px;font-size:9px;opacity:.58}@media print{.manual-rect-duration-tools{display:none!important}.wnmu-manual-note-overlay{box-shadow:none;background:#fff;border-color:#111;color:#000}}`; document.head.appendChild(st)}
function start(){styles();controls();patchStorage();document.addEventListener('contextmenu',e=>{let c=e.target.closest?.('.program-cell[data-entry-id]'); if(!c)return; selectedCell=c; selectedId=c.dataset.entryId||''; setTimeout(()=>setCtrls(selectedId,selectedCell),0)},true);document.addEventListener('click',e=>{if(e.target.closest?.('#drawRectBtn')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();saveNote();return} if(e.target.closest?.('#clearRectBtn,#clearMarksBtn')&&selectedId){let mt=meta();delete mt[selectedId];write(metaKey(),mt);setTimeout(renderSoon,80)}},true);let obs=new MutationObserver(renderSoon);obs.observe(document.getElementById('weekGrids')||document.body,{childList:true,subtree:true});addEventListener('resize',renderSoon);addEventListener('beforeprint',()=>setTimeout(render,50));setInterval(renderSoon,5000);renderSoon();let f=document.getElementById('versionFlag'); if(f&&!f.textContent.includes('manual note boxes'))f.textContent=`${f.textContent} • manual note boxes ${VER.replace('v','')}`}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true}); else start();
})();
